name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_API: api-service-repo
  ECR_REPOSITORY_AI: ai-service-repo

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push AI Service Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd ai_service_aws
        
        # Download ML models from S3 because they are too large for GitHub (267MB+)
        aws s3 sync s3://pae.ml.models/distilbert_categorization_model ./model_weights/distilbert_categorization_model
        
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_AI:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_AI:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_AI:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_AI:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_AI:latest

    - name: Build, tag, and push API Service Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd api_service_aws
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_API:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:latest

    - name: Trigger ECS Express Deployment (AI Service)
      run: |
        aws ecs update-service --cluster default --service ai-service-express --force-new-deployment --region ${{ env.AWS_REGION }}

    - name: Trigger ECS Express Deployment (API Service)
      run: |
        aws ecs update-service --cluster default --service api-service-express --force-new-deployment --region ${{ env.AWS_REGION }}
